import { Product, Category, CategoryOption, Locale } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: {
      en: 'Makeup Sponge in Case – Brown',
      hy: 'Դիմահարդարման սպունգ պատյանով – Շագանակագույն',
      ru: 'Спонж для макияжа в футляре Коричневый',
    },
    shortDescription: {
      en: 'Soft latex-free makeup sponge for smooth, even foundation application.',
      hy: 'Լատեքս չպարունակող փափուկ սպունգ՝ տոնային քսուքը հարթ ու հավասար քսելու համար։',
      ru: 'Идеальное нанесение тонального крема без разводов.',
    },
    description: {
      en: 'Ultra-soft, latex-free makeup sponge for even foundation application without absorbing excess product. The beveled edge makes application easier and more precise.',
      hy: 'Ուլտրափափուկ, լատեքս չպարունակող դիմահարդարման սպունգ, որն ապահովում է տոնային քսուքի հավասար բաշխում՝ առանց ավելորդ միջոցը ներծծելու։ Կտրված եզրը քսումը դարձնում է ավելի հարմար և ճշգրիտ։',
      ru: 'Ультрамягкие спонжи для макияжа, в составе которых нет латекса, за счет этого тон распределяет равномерно, не впитывает в себя много продукта. Спонж с усеченным краем что даёт ещё более удобное нанесение.',
    },
    price: 450,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-23-49-UGUkHEHnsWExMb5ffOstLwttUBhnQx.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-17-34-mBIpcT2RrL4wBIoCpnblCEatqonuod.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-33-34-May7ex9nujuJet5Q5Uthwhlvck5q9E.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-34-37-Y9xJEWMC9yPY8KS0vidqYEtTE4V2V4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/sponge%202%20color-GtqMDnOnZPnfDDq8D7nORwLcmDYRgo.JPG',
    ],
    videos: [],
    category: 'cosmetic_sponges',
    size: '1шт',
    sku: 'CSM-SP-001',
    stockQuantity: 15,
    bestseller: true,
  },
  {
    id: '2',
    name: {
      en: 'Makeup Sponge in Case – Black',
      hy: 'Դիմահարդարման սպունգ պատյանով – Սև',
      ru: 'Спонж для макияжа в футляре Черный',
    },
    shortDescription: {
      en: 'Soft latex-free makeup sponge for smooth, even foundation application.',
      hy: 'Լատեքս չպարունակող փափուկ սպունգ՝ տոնային քսուքը հարթ ու հավասար քսելու համար։',
      ru: 'Идеальное нанесение тонального крема без разводов.',
    },
    description: {
      en: 'Ultra-soft, latex-free makeup sponge for even foundation application without absorbing excess product. The beveled edge makes application easier and more precise.',
      hy: 'Ուլտրափափուկ, լատեքս չպարունակող դիմահարդարման սպունգ, որն ապահովում է տոնային քսուքի հավասար բաշխում՝ առանց ավելորդ միջոցը ներծծելու։ Կտրված եզրը քսումը դարձնում է ավելի հարմար և ճշգրիտ։',
      ru: 'Ультрамягкие спонжи для макияжа, в составе которых нет латекса, за счет этого тон распределяет равномерно, не впитывает в себя много продукта. Спонж с усеченным краем что даёт ещё более удобное нанесение.',
    },
    price: 450,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-06-15-EaWYWvfs3WuyLk1SEbxGzeAg81cnA0.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-15-24-JcVWnu8wy2Yu8T3zWY0zErwSjSgnLx.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-40-30-s2iQN5MM3xVhl1DaVju3HiRjTAzTvQ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-32-29-f4kOBb7zavanIcXSnXd67FxmICVC4N.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_8606-D119AkE7LjnqDqd4liXIyMHnXX3WAJ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/sponge%202%20color-Lvu7Irslhsv7KZKC1iNRve9ef8twvk.JPG',
    ],
    videos: [],
    category: 'cosmetic_sponges',
    size: '1шт',
    sku: 'CSM-SP-002',
    stockQuantity: 15,
    featured: true,
  },
  {
    id: '3',
    name: {
      en: 'Nude Lip Pencil-Lipstick 01',
      hy: 'Շուրթերի նյուդ մատիտ-շրթներկ 01',
      ru: 'Карандаш-помада для губ нюдовый 01',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Стойкий карандаш для губ, чётко очерчивает контур и предотвращает растекание.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-001',
    stockQuantity: 0,
  },
  {
    id: '4',
    name: {
      en: 'Nude Lip Pencil 02',
      hy: 'Շուրթերի նյուդ մատիտ 02',
      ru: 'Карандаш для губ нюдовый 02',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-002',
    stockQuantity: 0,
  },
  {
    id: '5',
    name: {
      en: 'Nude Lip Pencil 03',
      hy: 'Շուրթերի նյուդ մատիտ 03',
      ru: 'Карандаш для губ нюдовый 03',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-003',
    stockQuantity: 0,
  },
  {
    id: '6',
    name: {
      en: 'Nude Lip Pencil 04',
      hy: 'Շուրթերի նյուդ մատիտ 04',
      ru: 'Карандаш для губ нюдовый 04',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-004',
    stockQuantity: 0,
  },
  {
    id: '7',
    name: {
      en: 'Nude Lip Pencil 102',
      hy: 'Շուրթերի նյուդ մատիտ 102',
      ru: 'Карандаш для губ нюдовый 102',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7378_jpg-2cOgBCer1OTXBxnAM5vw2ulxBCUHFl.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7375_jpg-8C5bFlG1oR8aBLgm50ONCLFGXshxXE.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7373_jpg-eDiuf9pmzoQn75zh2n5ZKh1XSr6oHg.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7371-xEf1d6QOBy8HVd7BfL63zOmSrLSyyq.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7379-fzANNnJA789AQ9AkKnq2w7RK7GgI9b.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7380-1Q9HbXb0RK3LoVBE7PMWMG1UqE7ejz.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-005',
    stockQuantity: 20,
    featured: true,
    bestseller: true,
  },
  {
    id: '8',
    name: {
      en: 'Nude Lip Pencil 104',
      hy: 'Շուրթերի նյուդ մատիտ 104',
      ru: 'Карандаш для губ нюдовый 104',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7416_jpg-fWwnOztBBtsVap8JRKO2xxQSRsiWW3.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7417_jpg-Rj15V35JsfTJF1oyRZX6c7ktjtH1vK.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7413_jpg-0rz3nXAtlGNu5FbCnc19KFgKuBYV5S.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7414_jpg-Bzh4uopGyla8kkiUy8P2fp8OReR5J1.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7419_jpg-xdn3Xgrxo3bHG5aKYa6i9jR8q7owVJ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7421_jpg-oqvp1sskx8JMDqgTAs8XzrZmtaWM2b.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-006',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '9',
    name: {
      en: 'Nude Lip Pencil 106',
      hy: 'Շուրթերի նյուդ մատիտ 106',
      ru: 'Карандаш для губ нюдовый 106',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7357_jpg-1ayDKYZTBHsXtiAHHCCposHbeUQlUa.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7356_jpg-K0b2Bq06gYG5alTkmCiul08pdBjAdy.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7358_jpg-5IyoCZkalpuS5Py3oMMRVvtoxuw29u.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7351_jpg-eGSA7KTX5ctfI1FizHq2zE5kxLh0Gu.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7352_jpg-iUTioMriAwwjegMLtIZwf2wvb9UtXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7354_jpg-C0LUDKMaWVV9YuTSoehgeqinS7toPB.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7355_jpg-b3m68W0cCKh6zNS8jt3WfYCcdYnR9U.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-007',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '10',
    name: {
      en: 'Nude Lip Pencil 107',
      hy: 'Շուրթերի նյուդ մատիտ 107',
      ru: 'Карандаш для губ нюдовый 107',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7453_jpg-aDzhGDQGcP1RjvikdhBfadF3U6qhYj.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7452_jpg-xqE4qjw1uLtxowYgarCYH5JUx4OazM.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7448_jpg-LG4fJrmxP5x8Fd8zdLfhN2SisZ7Smb.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7449_jpg-yJtHhEg5bZtVFr4S1Tbgv2Z0QK34ye.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-008',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '11',
    name: {
      en: 'Nude Matte Lip Pencil 108',
      hy: 'Շուրթերի մատտե նյուդ մատիտ 108',
      ru: 'Карандаш для губ нюдовый матовый 108',
    },
    shortDescription: {
      en: 'Long-lasting matte nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց մատտե նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful matte nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ մատտե նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых матовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7439_jpg-ktI5dRwGxNnPvYp31TpJiVf86L3Gcf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7440_jpg-sCtKiweiPZCteyjmjZDCFHWQhvKQjq.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7443_jpg-9hPeIzPqQ2MpbcVfu0Zk0gC5C6Ddpp.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7432_jpg-qYRtTsdNvYmCY4OYq2CZ3r64yyBty3.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7433_jpg-c6JnbOQclq64NmSbRFqLTrc5Cz5ell.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5г',
    sku: 'CSM-LL-009',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '12',
    name: {
      en: 'Natural Radiant Glow Highlighter Stick',
      hy: 'Բնական փայլուն լուսարձակող սթիք',
      ru: 'Стик-хайлайтер с естественным сияющим блеском',
    },
    shortDescription: {
      en: 'highlighter stick for a natural, radiant glow with a creamy texture that blends easily.',
      hy: 'Բնական, փայլուն լուսարձակող սթիք՝ կրեմային հյուսվածքով, որը հեշտությամբ շերտավորվում է։',
      ru: 'Стик-хайлайтер для естественного сияния с кремовой текстурой, которая легко растушевывается.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-22-05-14-C8NmplTKY6QdlkzLXUY6OwEm7Jaizc.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4386-Mrz2BBpK21l6JVBbYLB9Otj44oyRve.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4397-oYppNWpnQLArlSUue0ToN8cQ04seej.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7г',
    sku: 'CSM-ST-001',
    stockQuantity: 20,
    featured: true,
    bestseller: true,
  },
  {
    id: '13',
    name: {
      en: 'Sculpting Touch Creamy Contour Stick',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք',
      ru: 'Скульптурирующий кремовый контурный стик',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-22-09-55-D1qEoavnvKSFMLD7lfumHlBy4kZ4Ti.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4387-nEySBOyKy0to1jNaDpW5uWPL0tt6XC.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4400-dTtmnSaw5SgIuve9Mya5zRVITdN6ve.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7г',
    sku: 'CSM-ST-002',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '14',
    name: {
      en: 'Sculpting Touch Creamy Contour Stick 501 Cold',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք 501 Սառը',
      ru: 'Скульптурирующий кремовый контурный стик 501 Холодный',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4420_jpg-7OpMU6UKh9Y7XFvBry89RtdSO5EDqV.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4387-JPXisYpGj0KOJJtxtyzIFWdWOHsua6.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4398-1lGtPrGX27iGzchTUX81hRHP9CDCDI.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7г',
    sku: 'CSM-ST-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '15',
    name: {
      en: 'On-the-glow Blush Stick',
      hy: 'Փայլող կարմրության սթիք',
      ru: 'Румяна-стик для сияния',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-21-48-03-I0ES9XyfbIovzONUfZ6P8WaqNjUR86.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4388-uPx1BpXThLJhwilulG6L0uuCQq8Uvk.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4399-B4FylwrDewa3IXGTgB6fq9tLZOknF7.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4427-pU6y379Q4Lzt1PCDFA4IXL74gH8uOP.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7г',
    sku: 'CSM-ST-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '16',
    name: {
      en: 'Ultra Shine Lip Gloss 01 PEACH',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 01 Դեղձ',
      ru: 'Блеск для губ ультра сияние 01 PEACH',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-42-48-RdLx365a7CyS3eyBg8DgDyBORn6ebf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1086-HU4cm6LU1vb8T6IiR65CHiCIqEOrra.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1091_jpg-o30uI6fgrKiNOU6YBrROUJgtEdVdAP.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1073-02KtTC2CiaGgpgly6klCR9NCbiIse8.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-wCcBKUaDsvteipGwyOaN1XNER7Igky.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-7YhmqOc3887YP695RkVlxuXuvfMjQr.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5мл',
    sku: 'CSM-LG-001',
    stockQuantity: 20,
    bestseller: true,
  },
  {
    id: '17',
    name: {
      en: 'Ultra Shine Lip Gloss 02 Baby Doll',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 02 Բեյբի Դոլլ',
      ru: 'Блеск для губ ультра сияние 02 Baby Doll',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-40-36-J1eBbg51NQuGxnYznp1tj7SSuNj9dP.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1080_jpg-Si8JUCzMH0HihselJOc9Ktr5zIydq7.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1090_jpg-M7RSgYiMyPQkdrCkoPfOaJGKiKF1W5.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1072-BwvjiW8hGaXFwk2CJkuvjbGtX6Zrob.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-DoJYsXwAYgEAXDf6AUyOMurQZpNJzj.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-URK4fEYymj4nGUwa0YNlxwGAkcYqVz.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5мл',
    sku: 'CSM-LG-002',
    stockQuantity: 20,
    featured: true,
  },
  {
    id: '18',
    name: {
      en: 'Ultra Shine Lip Gloss 03 Magic Shine',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 03 Կախարդական փայլ',
      ru: 'Блеск для губ ультра сияние 03 Magic Shine',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-37-57-I1S5p18ijQ4OpjVDQN6kLJmyfcqGUy.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1067_jpg-jagu7CXtk7ezEzBxnyX1VxC8SmTUj2.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1077_jpg-SN041qLLnoTeZXDDt596ZKY3KsWdae.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1088_jpg-BXSXLt72fNYH9GTgO424EaOTtZqw63.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-w43gsoQlLJVwRb4vIjAGF6V2nOGAbf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-8EZaAD9oHngpjsjNqjHb3Mbe1hPrG5.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5мл',
    sku: 'CSM-LG-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '19',
    name: {
      en: 'Ultra Shine Lip Gloss 04 Pink',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 04 Վարդագույն',
      ru: 'Блеск для губ ультра сияние 04 Pink',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-44-00-eoJgIIB2pZihmYTz4i52s7YUcACK24.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1082-VC3zfSEkeFNQ5b6v9B1HByw2lwMlh4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1075_jpg-bc3rs1hwFSxRm84rDsTX8hWz9dbUXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-j8WQwCZTx0tBzSf0rEarxpMDO86wJz.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-DshdFmzOlbDPCGchNHPPtByWaPTGAT.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5мл',
    sku: 'CSM-LG-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '20',
    name: {
      en: 'Ultra Shine Lip Gloss 05 Crystal',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 05 Բյուրեղ',
      ru: 'Блеск для губ ультра сияние 05 Crystal',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-44-00-eoJgIIB2pZihmYTz4i52s7YUcACK24.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1082-VC3zfSEkeFNQ5b6v9B1HByw2lwMlh4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1075_jpg-bc3rs1hwFSxRm84rDsTX8hWz9dbUXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-j8WQwCZTx0tBzSf0rEarxpMDO86wJz.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-DshdFmzOlbDPCGchNHPPtByWaPTGAT.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5мл',
    sku: 'CSM-LG-005',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '21',
    name: {
      en: 'Face and Body Highlighter, 101 Diamond',
      hy: 'Հայլայթեր դեմքի և մարմնի համար, 101 Diamond',
      ru: 'Хайлайтер для лица и тела сухой, 101 Diamond',
    },
    shortDescription: {
      en: 'Highlighter with a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    description: {
      en: 'A highlighter that has a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    price: 960,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9782_jpg-EujANwaBaHC84gmdRaK1Y8jkrw6DK0.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9775_jpg-9HpeaCP4jBUrtLp85NirtPSMYEqPJn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_04-02-2025-20-17-14-Js2xvGECjKG0cp7NTu4CXCoCphI86D.JPG',
    ],
    videos: [],
    category: 'highlighter',
    size: '5мл',
    sku: 'CSM-LB-001',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '22',
    name: {
      en: 'Face and Body Highlighter, 102 Gold',
      hy: 'Հայլայթեր դեմքի և մարմնի համար, 102 Gold',
      ru: 'Хайлайтер для лица и тела сухой, 102 Gold',
    },
    shortDescription: {
      en: 'Highlighter with a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    description: {
      en: 'A highlighter that has a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    price: 960,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9781_jpg-rQvQhK0Am16ffVSbGHatl8ngpWQC3s.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9776_jpg-S5yxSXP2WszwgKmnlocVBvoV8vTx4C.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_04-02-2025-20-15-37-z9uDu6C2w1WUFVicHwaMhZuvmX6oyL.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9784_jpg-QN6hJyyonc3STExlrexbXoRc4Wyc4j.JPG',
    ],
    videos: [],
    category: 'highlighter',
    size: '5мл',
    sku: 'CSM-LB-002',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '23',
    name: {
      en: 'Face and Body Highlighter, Pink Dark',
      hy: 'Հայլայթեր դեմքի և մարմնի համար, Pink Dark',
      ru: 'Хайлайтер для лица и тела сухой, Pink Dark',
    },
    shortDescription: {
      en: 'Highlighter with a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    description: {
      en: 'A highlighter that has a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    price: 960,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_2079_jpg-WcwwggoiY0ehhtt96eaL9hl2tqMCB0.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_2076_jpg-HCePY2UBvK2YD4OCwkwTK7iy7bpSwc.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_2077_jpg-blqyueOjcY4JxHUzmcBA2cb58LabB6.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_04-02-2025-20-13-08-bwSj2AQsOaRpivt1Gw0j5c5l0JSDwt.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_2136_jpg-YsQrE1UTWwz1BzySUqIodse0vxMROe.JPG',
    ],
    videos: [],
    category: 'highlighter',
    size: '5мл',
    sku: 'CSM-LB-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '24',
    name: {
      en: 'Face and Body Highlighter, Pink Light',
      hy: 'Հայլայթեր դեմքի և մարմնի համար, Pink Light',
      ru: 'Хайлайтер для лица и тела сухой, Pink Light',
    },
    shortDescription: {
      en: 'Highlighter with a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    description: {
      en: 'A highlighter that has a beautiful glow, contains large glitter particles so it can be used as an eye sparkle. It is best applied to damp skin with your fingers.',
      hy: 'Հայլայթեր` իր գեղեցիկ փայլով, պարունակում է մեծ փայլուն մասնիկներ, այնպես որ կարող է օգտագործվել որպես աչքերի փայլ: Լավագույնն է կիրառել խոնավ մաշկի վրա մատներով:',
      ru: 'Хайлайтер, который имеет красивое свечение, в составе крупные частички блесток поэтому можно использовать как спаркл на глазах. Лучше всего наносится на влажную кожу пальчиков.',
    },
    price: 960,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9783_jpg-orXz4CNOhYe4u8v5n5oRkk57wujRTC.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9778_jpg-i4pjpnYmrwh1v951TEbJEbOmKN4vam.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_04-02-2025-20-16-52-VUQGZitJERIZtPMR7t60to5os5RQbV.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_9761_jpg-2c3PGnSlY94L0EBdj4Djv8Z8aVHk2I.JPG',
    ],
    videos: [],
    category: 'highlighter',
    size: '5мл',
    sku: 'CSM-LB-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '25',
    name: {
      en: 'Blush for Face 201',
      hy: 'Ռումյան դեմքի համար 201',
      ru: 'Румяна для лица 201',
    },
    shortDescription: {
      en: 'Blush with shimmer that is easy to blend and gives a beautiful glow, best applied on dry powdered skin.',
      hy: 'Շիմերով ռումյան, որը հեշտությամբ շերտավորվում է և գեղեցիկ փայլ է հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Румяна с шимером, которые легко тушуются и придают красивое свечение, лучше всего наносить на сухую припудренную кожу.',
    },
    description: {
      en: 'Morena cosmetics dry blushes are easy to blend and give a beautiful glow thanks to the shimmer in the texture. Ideal for applying on dry powdered skin, after applying it, you can even skip using a highlighter. The shades are universal and will suit everyone, giving freshness to the makeup. Blushes with shimmer are easy to blend and give a beautiful glow, best applied on dry powdered skin.',
      hy: 'Morena cosmetics չոր երանգավորիչները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, շնորհիվ շիմերի հյուսվածքի մեջ: Իդեալական է կիրառել չոր պուդրացված մաշկի վրա, այն կիրառելուց հետո նույնիսկ կարող եք չօգտագործել հայլայթեր: Տոները համընդհանուր են և կսազեն բոլորին, հաղորդելով թարմություն դիմահարդարմանը: Շիմերով ռումյանները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Сухие румяна Morena cosmetics легко тушуется и даёт красивое свечение, благодаря шимеру в текстуре. Идеально наносить на ю припудренную кожу, после его нанесение, можно даже не использовать хайлайтер. Оттенки универсальны и подойдут всем, придав макияжу свежести. Румяна с шимером, легко тушуется и даёт красивое свечение, лучше наносить на сухую припудренную кожу.',
    },
    price: 1600,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1101-22rDYgGxJL1pnFeyMMQ1mf1DSN1EfL.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1102_jpg-tH0ACfigG2N6i9F6CRT6l49SrGeBmp.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1100-S7GnOjlE3si1VBk8pDiOdb8qn9PLSr.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1109_jpg-gyRl7zmcENUImPqe3HZWx9j36usG90.JPG',
    ],
    videos: [],
    category: 'blush',
    size: '5мл',
    sku: 'CSM-BL-001',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '26',
    name: {
      en: 'Blush for Face 202',
      hy: 'Ռումյան դեմքի համար 202',
      ru: 'Румяна для лица 202',
    },
    shortDescription: {
      en: 'Blush with shimmer that is easy to blend and gives a beautiful glow, best applied on dry powdered skin.',
      hy: 'Շիմերով ռումյան, որը հեշտությամբ շերտավորվում է և գեղեցիկ փայլ է հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Румяна с шимером, которые легко тушуются и придают красивое свечение, лучше всего наносить на сухую припудренную кожу.',
    },
    description: {
      en: 'Morena cosmetics dry blushes are easy to blend and give a beautiful glow thanks to the shimmer in the texture. Ideal for applying on dry powdered skin, after applying it, you can even skip using a highlighter. The shades are universal and will suit everyone, giving freshness to the makeup. Blushes with shimmer are easy to blend and give a beautiful glow, best applied on dry powdered skin.',
      hy: 'Morena cosmetics չոր երանգավորիչները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, շնորհիվ շիմերի հյուսվածքի մեջ: Իդեալական է կիրառել չոր պուդրացված մաշկի վրա, այն կիրառելուց հետո նույնիսկ կարող եք չօգտագործել հայլայթեր: Տոները համընդհանուր են և կսազեն բոլորին, հաղորդելով թարմություն դիմահարդարմանը: Շիմերով ռումյանները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Сухие румяна Morena cosmetics легко тушуется и даёт красивое свечение, благодаря шимеру в текстуре. Идеально наносить на ю припудренную кожу, после его нанесение, можно даже не использовать хайлайтер. Оттенки универсальны и подойдут всем, придав макияжу свежести. Румяна с шимером, легко тушуется и даёт красивое свечение, лучше наносить на сухую припудренную кожу.',
    },
    price: 1600,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1106_jpg-uCf9MexOMB3FnQn7kZVSk8EnWVQheN.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1105_jpg-UolFx3SnPbuaCXXXSG36448upHP3Xf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1100-wcd1JWwzOrBs7JBH3aWE3oANKmzuMd.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1111_jpg-SojDOARZoSIPDdovj8DDl8wtHXyzGq.JPG',
    ],
    videos: [],
    category: 'blush',
    size: '10мл',
    sku: 'CSM-BL-002',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '27',
    name: {
      en: 'Blush for Face 203',
      hy: 'Ռումյան դեմքի համար 203',
      ru: 'Румяна для лица 203',
    },
    shortDescription: {
      en: 'Blush with shimmer that is easy to blend and gives a beautiful glow, best applied on dry powdered skin.',
      hy: 'Շիմերով ռումյան, որը հեշտությամբ շերտավորվում է և գեղեցիկ փայլ է հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Румяна с шимером, которые легко тушуются и придают красивое свечение, лучше всего наносить на сухую припудренную кожу.',
    },
    description: {
      en: 'Morena cosmetics dry blushes are easy to blend and give a beautiful glow thanks to the shimmer in the texture. Ideal for applying on dry powdered skin, after applying it, you can even skip using a highlighter. The shades are universal and will suit everyone, giving freshness to the makeup. Blushes with shimmer are easy to blend and give a beautiful glow, best applied on dry powdered skin.',
      hy: 'Morena cosmetics չոր երանգավորիչները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, շնորհիվ շիմերի հյուսվածքի մեջ: Իդեալական է կիրառել չոր պուդրացված մաշկի վրա, այն կիրառելուց հետո նույնիսկ կարող եք չօգտագործել հայլայթեր: Տոները համընդհանուր են և կսազեն բոլորին, հաղորդելով թարմություն դիմահարդարմանը: Շիմերով ռումյանները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Сухие румяна Morena cosmetics легко тушуется и даёт красивое свечение, благодаря шимеру в текстуре. Идеально наносить на ю припудренную кожу, после его нанесение, можно даже не использовать хайлайтер. Оттенки универсальны и подойдут всем, придав макияжу свежести. Румяна с шимером, легко тушуется и даёт красивое свечение, лучше наносить на сухую припудренную кожу.',
    },
    price: 1600,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1104-9RVhvZ0iD66hebq8y58dIrFrChPdl2.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1103_jpg-hR6Xui3atzLOZSWBiDPX5rirdXswKB.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1100-M1pghHAxbgzNW0GOtY3G7D4JpXFdqw.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1112_jpg-0Jx9CivOFbzPxdBZVU2bCcfpdeu46X.JPG',
    ],
    videos: [],
    category: 'blush',
    size: '10мл',
    sku: 'CSM-BL-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '28',
    name: {
      en: 'Blush for Face 204',
      hy: 'Ռումյան դեմքի համար 204',
      ru: 'Румяна для лица 204',
    },
    shortDescription: {
      en: 'Blush with shimmer that is easy to blend and gives a beautiful glow, best applied on dry powdered skin.',
      hy: 'Շիմերով ռումյան, որը հեշտությամբ շերտավորվում է և գեղեցիկ փայլ է հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Румяна с шимером, которые легко тушуются и придают красивое свечение, лучше всего наносить на сухую припудренную кожу.',
    },
    description: {
      en: 'Morena cosmetics dry blushes are easy to blend and give a beautiful glow thanks to the shimmer in the texture. Ideal for applying on dry powdered skin, after applying it, you can even skip using a highlighter. The shades are universal and will suit everyone, giving freshness to the makeup. Blushes with shimmer are easy to blend and give a beautiful glow, best applied on dry powdered skin.',
      hy: 'Morena cosmetics չոր երանգավորիչները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, շնորհիվ շիմերի հյուսվածքի մեջ: Իդեալական է կիրառել չոր պուդրացված մաշկի վրա, այն կիրառելուց հետո նույնիսկ կարող եք չօգտագործել հայլայթեր: Տոները համընդհանուր են և կսազեն բոլորին, հաղորդելով թարմություն դիմահարդարմանը: Շիմերով ռումյանները հեշտությամբ շերտավորվում են և գեղեցիկ փայլ են հաղորդում, լավագույնը կիրառել չոր պուդրացված մաշկի վրա:',
      ru: 'Сухие румяна Morena cosmetics легко тушуется и даёт красивое свечение, благодаря шимеру в текстуре. Идеально наносить на ю припудренную кожу, после его нанесение, можно даже не использовать хайлайтер. Оттенки универсальны и подойдут всем, придав макияжу свежести. Румяна с шимером, легко тушуется и даёт красивое свечение, лучше наносить на сухую припудренную кожу.',
    },
    price: 1600,
    images: [],
    videos: [],
    category: 'blush',
    size: '10мл',
    sku: 'CSM-BL-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '29',
    name: {
      en: 'Makeup Fixer Spray Silver',
      hy: 'Դիմահարդարման ֆիքսիչ սփրեյ Silver',
      ru: 'Спрей-фиксатор для макияжа Silver',
    },
    shortDescription: {
      en: 'Makeup Fixer Spray',
      hy: 'Դիմահարդարման ֆիքսիչ սփրեյ',
      ru: 'Спрей-фиксатор для макияжа',
    },
    description: {
      en: 'Morena Cosmetics 2-in-1 Spray has a liquid consistency with a pleasant scent. It can be used both as a makeup fixer and as a refreshing spray throughout the day. The formula is designed to keep your makeup in place for hours, preventing smudging and fading. It also provides hydration to the skin, leaving it feeling fresh and revitalized.',
      hy: 'Morena Cosmetics 2-ը 1-ում սփրեյը ունի հեղուկ կոնսիստենցիա և հաճելի հոտ: Այն կարող է օգտագործվել և որպես դիմահարդարման ֆիքսիչ, և որպես թարմացնող սփրեյ ամբողջ օրվա ընթացքում: Ֆորմուլան նախատեսված է պահելու ձեր դիմահարդարումը տեղում ժամերով, կանխելով շփումը և մաշվելը: Այն նաև ապահովում է խոնավացում մաշկին, թողնելով այն թարմ և վերականգնված զգացողությամբ:',
      ru: 'Спрей 2в1 имеет жидкую консистенцию с приятной отдушкой. Его можно использовать как фиксатор макияжа, так и освежающий спрей в течение дня. Формула разработана для того, чтобы держать макияж на месте в течение часов, предотвращая размазывание и выцветание. Также обеспечивает увлажнение кожи, оставляя ее свежей и обновленной.',
    },
    price: 755,
    images: [],
    videos: [],
    category: 'makeup_fixer',
    size: '80мл',
    sku: 'CSM-MF-001',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '30',
    name: {
      en: 'Makeup Fixer Spray Gold',
      hy: 'Դիմահարդարման ֆիքսիչ սփրեյ Gold',
      ru: 'Спрей-фиксатор для макияжа Gold',
    },
    shortDescription: {
      en: 'Makeup Fixer Spray',
      hy: 'Դիմահարդարման ֆիքսիչ սփրեյ',
      ru: 'Спрей-фиксатор для макияжа',
    },
    description: {
      en: 'Morena Cosmetics 2-in-1 Spray has a liquid consistency with a pleasant scent. It can be used both as a makeup fixer and as a refreshing spray throughout the day. The formula is designed to keep your makeup in place for hours, preventing smudging and fading. It also provides hydration to the skin, leaving it feeling fresh and revitalized.',
      hy: 'Morena Cosmetics 2-ը 1-ում սփրեյը ունի հեղուկ կոնսիստենցիա և հաճելի հոտ: Այն կարող է օգտագործվել և որպես դիմահարդարման ֆիքսիչ, և որպես թարմացնող սփրեյ ամբողջ օրվա ընթացքում: Ֆորմուլան նախատեսված է պահելու ձեր դիմահարդարումը տեղում ժամերով, կանխելով շփումը և մաշվելը: Այն նաև ապահովում է խոնավացում մաշկին, թողնելով այն թարմ և վերականգնված զգացողությամբ:',
      ru: 'Спрей 2в1 имеет жидкую консистенцию с приятной отдушкой. Его можно использовать как фиксатор макияжа, так и освежающий спрей в течение дня. Формула разработана для того, чтобы держать макияж на месте в течение часов, предотвращая размазывание и выцветание. Также обеспечивает увлажнение кожи, оставляя ее свежей и обновленной.',
    },
    price: 755,
    images: [],
    videos: [],
    category: 'makeup_fixer',
    size: '80мл',
    sku: 'CSM-MF-002',
    stockQuantity: 20,
    featured: false,
  },
]

export const categories: CategoryOption[] = [
  {
    value: 'cosmetic_sponges',
    label: {
      en: 'Cosmetic Sponges',
      hy: 'Կոսմետիկ սպունգեր',
      ru: 'Косметические спонжи',
    },
  },
  {
    value: 'lip_liner',
    label: {
      en: 'Lip Liner',
      hy: 'Շրթունքների մատիտ',
      ru: 'Карандаш для губ',
    },
  },
  {
    value: 'blush',
    label: { en: 'Blush', hy: 'Երանգավորիչ', ru: 'Румяна' },
  },
  { value: 'stick', label: { en: 'Stick', hy: 'Սթիք', ru: 'Стик' } },
  {
    value: 'lip_gloss',
    label: { en: 'Lip Gloss', hy: 'Շրթունքների փայլ', ru: 'Блеск для губ' },
  },
  {
    value: 'highlighter',
    label: { en: 'Highlighter', hy: 'Լուսավորիչ', ru: 'Сияющие румяна' },
  },
  {
    value: 'concealer',
    label: { en: 'Concealer', hy: 'Կոնսիլյար', ru: 'Консилер' },
  },
  {
    value: 'false_eyelashes',
    label: {
      en: 'False Eyelashes',
      hy: 'Թարթիչներ',
      ru: 'Накладные ресницы',
    },
  },
  {
    value: 'makeup_fixer',
    label: {
      en: 'Makeup Fixer',
      hy: 'Մակյաժի ֆիքսիչ',
      ru: 'Фиксатор макияжа',
    },
  },
]

export const allSizes = [...new Set(products.map((p) => p.size))].sort()

/** Returns the localized display label for a category value */
export function getCategoryLabel(value: Category, locale: Locale): string {
  return categories.find((c) => c.value === value)?.label[locale] ?? value
}

export const getFeaturedProducts = () => products.filter((p) => p.featured)
export const getBestsellers = () => products.filter((p) => p.bestseller)
export const getProductById = (id: string) => products.find((p) => p.id === id)
export const getProductsByCategory = (category: Category) =>
  products.filter((p) => p.category === category)
