import { Product, Category, CategoryOption, Locale } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: {
      en: 'Makeup Sponge in Case – Brown',
      hy: 'Դիմահարդարման սպունգ պատյանով – Շագանակագույն',
      ru: 'Спонж для макияжа в футляре Коричневый',
    },
    shortDescription: {
      en: 'Soft latex-free makeup sponge for smooth, even foundation application.',
      hy: 'Լատեքս չպարունակող փափուկ սպունգ՝ տոնային քսուքը հարթ ու հավասար քսելու համար։',
      ru: 'Идеальное нанесение тонального крема без разводов.',
    },
    description: {
      en: 'Ultra-soft, latex-free makeup sponge for even foundation application without absorbing excess product. The beveled edge makes application easier and more precise.',
      hy: 'Ուլտրափափուկ, լատեքս չպարունակող դիմահարդարման սպունգ, որն ապահովում է տոնային քսուքի հավասար բաշխում՝ առանց ավելորդ միջոցը ներծծելու։ Կտրված եզրը քսումը դարձնում է ավելի հարմար և ճշգրիտ։',
      ru: 'Ультрамягкие спонжи для макияжа, в составе которых нет латекса, за счет этого тон распределяет равномерно, не впитывает в себя много продукта. Спонж с усеченным краем что даёт ещё более удобное нанесение.',
    },
    price: 450,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-23-49-UGUkHEHnsWExMb5ffOstLwttUBhnQx.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-17-34-mBIpcT2RrL4wBIoCpnblCEatqonuod.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-33-34-May7ex9nujuJet5Q5Uthwhlvck5q9E.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-34-37-Y9xJEWMC9yPY8KS0vidqYEtTE4V2V4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/sponge%202%20color-GtqMDnOnZPnfDDq8D7nORwLcmDYRgo.JPG',
    ],
    videos: [],
    category: 'cosmetic_sponges',
    size: '1 pcs',
    sku: 'CSM-SP-001',
    stockQuantity: 15,
    bestseller: true,
  },
  {
    id: '2',
    name: {
      en: 'Makeup Sponge in Case – Black',
      hy: 'Դիմահարդարման սպունգ պատյանով – Սև',
      ru: 'Спонж для макияжа в футляре Черный',
    },
    shortDescription: {
      en: 'Soft latex-free makeup sponge for smooth, even foundation application.',
      hy: 'Լատեքս չպարունակող փափուկ սպունգ՝ տոնային քսուքը հարթ ու հավասար քսելու համար։',
      ru: 'Идеальное нанесение тонального крема без разводов.',
    },
    description: {
      en: 'Ultra-soft, latex-free makeup sponge for even foundation application without absorbing excess product. The beveled edge makes application easier and more precise.',
      hy: 'Ուլտրափափուկ, լատեքս չպարունակող դիմահարդարման սպունգ, որն ապահովում է տոնային քսուքի հավասար բաշխում՝ առանց ավելորդ միջոցը ներծծելու։ Կտրված եզրը քսումը դարձնում է ավելի հարմար և ճշգրիտ։',
      ru: 'Ультрамягкие спонжи для макияжа, в составе которых нет латекса, за счет этого тон распределяет равномерно, не впитывает в себя много продукта. Спонж с усеченным краем что даёт ещё более удобное нанесение.',
    },
    price: 450,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-06-15-EaWYWvfs3WuyLk1SEbxGzeAg81cnA0.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-15-24-JcVWnu8wy2Yu8T3zWY0zErwSjSgnLx.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-40-30-s2iQN5MM3xVhl1DaVju3HiRjTAzTvQ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-04-2024-23-32-29-f4kOBb7zavanIcXSnXd67FxmICVC4N.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_8606-D119AkE7LjnqDqd4liXIyMHnXX3WAJ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/sponge%202%20color-Lvu7Irslhsv7KZKC1iNRve9ef8twvk.JPG',
    ],
    videos: [],
    category: 'cosmetic_sponges',
    size: '1 pcs',
    sku: 'CSM-SP-002',
    stockQuantity: 15,
    featured: true,
  },
  {
    id: '3',
    name: {
      en: 'Nude Lip Pencil-Lipstick 01',
      hy: 'Շուրթերի նյուդ մատիտ-շրթներկ 01',
      ru: 'Карандаш-помада для губ нюдовый 01',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Стойкий карандаш для губ, чётко очерчивает контур и предотвращает растекание.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-001',
    stockQuantity: 0,
  },
  {
    id: '4',
    name: {
      en: 'Nude Lip Pencil 02',
      hy: 'Շուրթերի նյուդ մատիտ 02',
      ru: 'Карандаш для губ нюдовый 02',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-002',
    stockQuantity: 0,
  },
  {
    id: '5',
    name: {
      en: 'Nude Lip Pencil 03',
      hy: 'Շուրթերի նյուդ մատիտ 03',
      ru: 'Карандаш для губ нюдовый 03',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-003',
    stockQuantity: 0,
  },
  {
    id: '6',
    name: {
      en: 'Nude Lip Pencil 04',
      hy: 'Շուրթերի նյուդ մատիտ 04',
      ru: 'Карандаш для губ нюдовый 04',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-004',
    stockQuantity: 0,
  },
  {
    id: '7',
    name: {
      en: 'Nude Lip Pencil 102',
      hy: 'Շուրթերի նյուդ մատիտ 102',
      ru: 'Карандаш для губ нюдовый 102',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7378_jpg-2cOgBCer1OTXBxnAM5vw2ulxBCUHFl.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7375_jpg-8C5bFlG1oR8aBLgm50ONCLFGXshxXE.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7373_jpg-eDiuf9pmzoQn75zh2n5ZKh1XSr6oHg.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7371-xEf1d6QOBy8HVd7BfL63zOmSrLSyyq.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7379-fzANNnJA789AQ9AkKnq2w7RK7GgI9b.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7380-1Q9HbXb0RK3LoVBE7PMWMG1UqE7ejz.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-005',
    stockQuantity: 20,
    featured: true,
    bestseller: true,
  },
  {
    id: '8',
    name: {
      en: 'Nude Lip Pencil 104',
      hy: 'Շուրթերի նյուդ մատիտ 104',
      ru: 'Карандаш для губ нюдовый 104',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7416_jpg-fWwnOztBBtsVap8JRKO2xxQSRsiWW3.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7417_jpg-Rj15V35JsfTJF1oyRZX6c7ktjtH1vK.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7413_jpg-0rz3nXAtlGNu5FbCnc19KFgKuBYV5S.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7414_jpg-Bzh4uopGyla8kkiUy8P2fp8OReR5J1.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7419_jpg-xdn3Xgrxo3bHG5aKYa6i9jR8q7owVJ.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7421_jpg-oqvp1sskx8JMDqgTAs8XzrZmtaWM2b.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-006',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '9',
    name: {
      en: 'Nude Lip Pencil 106',
      hy: 'Շուրթերի նյուդ մատիտ 106',
      ru: 'Карандаш для губ нюдовый 106',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7357_jpg-1ayDKYZTBHsXtiAHHCCposHbeUQlUa.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7356_jpg-K0b2Bq06gYG5alTkmCiul08pdBjAdy.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7358_jpg-5IyoCZkalpuS5Py3oMMRVvtoxuw29u.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7351_jpg-eGSA7KTX5ctfI1FizHq2zE5kxLh0Gu.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7352_jpg-iUTioMriAwwjegMLtIZwf2wvb9UtXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7354_jpg-C0LUDKMaWVV9YuTSoehgeqinS7toPB.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7355_jpg-b3m68W0cCKh6zNS8jt3WfYCcdYnR9U.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-007',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '10',
    name: {
      en: 'Nude Lip Pencil 107',
      hy: 'Շուրթերի նյուդ մատիտ 107',
      ru: 'Карандаш для губ нюдовый 107',
    },
    shortDescription: {
      en: 'Long-lasting nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы.\nМожно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7453_jpg-aDzhGDQGcP1RjvikdhBfadF3U6qhYj.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7452_jpg-xqE4qjw1uLtxowYgarCYH5JUx4OazM.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7448_jpg-LG4fJrmxP5x8Fd8zdLfhN2SisZ7Smb.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7449_jpg-yJtHhEg5bZtVFr4S1Tbgv2Z0QK34ye.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-008',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '11',
    name: {
      en: 'Nude Matte Lip Pencil 108',
      hy: 'Շուրթերի մատտե նյուդ մատիտ 108',
      ru: 'Карандаш для губ нюдовый матовый 108',
    },
    shortDescription: {
      en: 'Long-lasting matte nude lip pencil for precise contouring and smooth blending.',
      hy: 'Երկարակյաց մատտե նյուդ շուրթերի մատիտ՝ հստակ ուրվագծման և նուրբ շերտավորման համար։',
      ru: 'Двухтонный карандаш для эффекта омбре на губах за секунды.',
    },
    description: {
      en: 'Lip pencils in beautiful matte nude shades that do not dry out your lips. They can be used for both precise contouring and soft blending. The waxy texture glides on smoothly, while the versatile shades suit most users. They perfectly complement both daytime and evening makeup.',
      hy: 'Շուրթերի մատիտներ գեղեցիկ մատտե նյուդ երանգներով, որոնք չեն չորացնում շուրթերը։ Դրանք կարելի է օգտագործել ինչպես հստակ ուրվագծման, այնպես էլ նուրբ շերտավորման համար։ Մատիտներն ունեն մոմային հյուսվածք, փափուկ են քսվում, իսկ ունիվերսալ երանգները կհամապատասխանեն շատերին։ Դրանք հիանալի լրացնում են ինչպես առօրյա, այնպես էլ երեկոյան դիմահարդարումը։',
      ru: 'Карандаш для губ в самых красивых нюдовых матовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши для губ Morena cosmetics в самых красивых нюдовых оттенках, не сушат губы. Можно использовать как просто контур, так и в растушевке. Карандаши имеют восковую текстуру, очень мягкие в нанесении, все оттенки универсальны и подойдут большинству пользователей. Идеально дополнят макияж как вечерний, так и дневной.',
    },
    price: 350,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7439_jpg-ktI5dRwGxNnPvYp31TpJiVf86L3Gcf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7440_jpg-sCtKiweiPZCteyjmjZDCFHWQhvKQjq.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7443_jpg-9hPeIzPqQ2MpbcVfu0Zk0gC5C6Ddpp.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7432_jpg-qYRtTsdNvYmCY4OYq2CZ3r64yyBty3.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_7433_jpg-c6JnbOQclq64NmSbRFqLTrc5Cz5ell.JPG',
    ],
    videos: [],
    category: 'lip_liner',
    size: '5g',
    sku: 'CSM-LL-009',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '12',
    name: {
      en: 'Natural Radiant Glow Highlighter Stick',
      hy: 'Բնական փայլուն լուսարձակող սթիք',
      ru: 'Стик-хайлайтер с естественным сияющим блеском',
    },
    shortDescription: {
      en: 'highlighter stick for a natural, radiant glow with a creamy texture that blends easily.',
      hy: 'Բնական, փայլուն լուսարձակող սթիք՝ կրեմային հյուսվածքով, որը հեշտությամբ շերտավորվում է։',
      ru: 'Стик-хайлайтер для естественного сияния с кремовой текстурой, которая легко растушевывается.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-22-05-14-C8NmplTKY6QdlkzLXUY6OwEm7Jaizc.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4386-Mrz2BBpK21l6JVBbYLB9Otj44oyRve.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4397-oYppNWpnQLArlSUue0ToN8cQ04seej.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7g',
    sku: 'CSM-ST-001',
    stockQuantity: 20,
    featured: true,
    bestseller: true,
  },
  {
    id: '13',
    name: {
      en: 'Sculpting Touch Creamy Contour Stick',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք',
      ru: 'Скульптурирующий кремовый контурный стик',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-22-09-55-D1qEoavnvKSFMLD7lfumHlBy4kZ4Ti.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4387-nEySBOyKy0to1jNaDpW5uWPL0tt6XC.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4400-dTtmnSaw5SgIuve9Mya5zRVITdN6ve.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7g',
    sku: 'CSM-ST-002',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '14',
    name: {
      en: 'Sculpting Touch Creamy Contour Stick 501 Cold',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք 501 Սառը',
      ru: 'Скульптурирующий кремовый контурный стик 501 Холодный',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4420_jpg-7OpMU6UKh9Y7XFvBry89RtdSO5EDqV.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4387-JPXisYpGj0KOJJtxtyzIFWdWOHsua6.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4398-1lGtPrGX27iGzchTUX81hRHP9CDCDI.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7g',
    sku: 'CSM-ST-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '15',
    name: {
      en: 'On-the-glow Blush Stick',
      hy: 'Փայլող կարմրության սթիք',
      ru: 'Румяна-стик для сияния',
    },
    shortDescription: {
      en: 'Creamy contour stick for sculpting and defining facial features with a blendable formula.',
      hy: 'Սկուլպտուրային շեշտադրող կրեմային կոնտուրային սթիք՝ հեշտությամբ շերտավորվող ֆորմուլայով։',
      ru: 'Кремовый контурирующий стик для скульптурирования и определения черт лица с легкой в растушевке формулой.',
    },
    description: {
      en: 'Morena cosmetics sticks are designed in a convenient format for creating the perfect makeup look. The product has a creamy texture that blends easily. It can be applied with a sponge or brush. The product does not run and has good staying power, high pigmentation, and the ability to adapt to skin tone.',
      hy: 'Ստիկեր՝ հարմար ձևաչափով, որը թույլ է տալիս ստեղծել կատարյալ դիմահարդարում։ Ապրանքը ունի կրեմային հյուսվածք, որը հեշտությամբ շերտավորվում է։ Կարելի է քսել սպունգով կամ խոզանակով։ Ապրանքը չի հոսում և ունի լավ կայունություն, ունի բարձր պիգմենտացիա և ունի հատկություն՝ հարմարեցվելու մաշկի գույնին:',
      ru: 'Стики Morena cosmetics сделаны в удобном формате для создания идеального макияжа.Продукт имеет кремовую текстуру, которая легко растушевывается. Можно наносить спонжиком или кисточкой. Продукт не течёт и имеет хорошую стойкость, обладает высокой пигментацией и имеет свойство подстроиться под оттенок кожи.',
    },
    price: 660,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_09-01-2025-21-48-03-I0ES9XyfbIovzONUfZ6P8WaqNjUR86.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4388-uPx1BpXThLJhwilulG6L0uuCQq8Uvk.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4399-B4FylwrDewa3IXGTgB6fq9tLZOknF7.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_4427-pU6y379Q4Lzt1PCDFA4IXL74gH8uOP.JPG',
    ],
    videos: [],
    category: 'stick',
    size: '7g',
    sku: 'CSM-ST-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '16',
    name: {
      en: 'Ultra Shine Lip Gloss 01 PEACH',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 01 Դեղձ',
      ru: 'Блеск для губ ультра сияние 01 PEACH',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-42-48-RdLx365a7CyS3eyBg8DgDyBORn6ebf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1086-HU4cm6LU1vb8T6IiR65CHiCIqEOrra.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1091_jpg-o30uI6fgrKiNOU6YBrROUJgtEdVdAP.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1073-02KtTC2CiaGgpgly6klCR9NCbiIse8.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-wCcBKUaDsvteipGwyOaN1XNER7Igky.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-7YhmqOc3887YP695RkVlxuXuvfMjQr.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5ml',
    sku: 'CSM-LG-001',
    stockQuantity: 20,
    bestseller: true,
  },
  {
    id: '17',
    name: {
      en: 'Ultra Shine Lip Gloss 02 Baby Doll',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 02 Բեյբի Դոլլ',
      ru: 'Блеск для губ ультра сияние 02 Baby Doll',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-40-36-J1eBbg51NQuGxnYznp1tj7SSuNj9dP.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1080_jpg-Si8JUCzMH0HihselJOc9Ktr5zIydq7.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1090_jpg-M7RSgYiMyPQkdrCkoPfOaJGKiKF1W5.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1072-BwvjiW8hGaXFwk2CJkuvjbGtX6Zrob.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-DoJYsXwAYgEAXDf6AUyOMurQZpNJzj.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-URK4fEYymj4nGUwa0YNlxwGAkcYqVz.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5ml',
    sku: 'CSM-LG-002',
    stockQuantity: 20,
    featured: true,
  },
  {
    id: '18',
    name: {
      en: 'Ultra Shine Lip Gloss 03 Magic Shine',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 03 Կախարդական փայլ',
      ru: 'Блеск для губ ультра сияние 03 Magic Shine',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-37-57-I1S5p18ijQ4OpjVDQN6kLJmyfcqGUy.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1067_jpg-jagu7CXtk7ezEzBxnyX1VxC8SmTUj2.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1077_jpg-SN041qLLnoTeZXDDt596ZKY3KsWdae.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1088_jpg-BXSXLt72fNYH9GTgO424EaOTtZqw63.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-w43gsoQlLJVwRb4vIjAGF6V2nOGAbf.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-8EZaAD9oHngpjsjNqjHb3Mbe1hPrG5.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5ml',
    sku: 'CSM-LG-003',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '19',
    name: {
      en: 'Ultra Shine Lip Gloss 04 Pink',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 04 Վարդագույն',
      ru: 'Блеск для губ ультра сияние 04 Pink',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-44-00-eoJgIIB2pZihmYTz4i52s7YUcACK24.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1082-VC3zfSEkeFNQ5b6v9B1HByw2lwMlh4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1075_jpg-bc3rs1hwFSxRm84rDsTX8hWz9dbUXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-j8WQwCZTx0tBzSf0rEarxpMDO86wJz.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-DshdFmzOlbDPCGchNHPPtByWaPTGAT.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5ml',
    sku: 'CSM-LG-004',
    stockQuantity: 20,
    featured: false,
  },
  {
    id: '20',
    name: {
      en: 'Ultra Shine Lip Gloss 05 Crystal',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ 05 Բյուրեղ',
      ru: 'Блеск для губ ультра сияние 05 Crystal',
    },
    shortDescription: {
      en: 'Ultra-shiny lip gloss with a non-sticky formula for a comfortable wear.',
      hy: 'Ուլտրա փայլուն շրթունքների փայլ՝ առանց կպչուն ֆորմուլայով՝ հարմարավետ կրելու համար։',
      ru: 'Ультра сияющий блеск для губ с не липкой формулой для комфортного ношения.',
    },
    description: {
      en: 'Morena Cosmetics Ultra Shine Lip Gloss will give your lips a seductive peachy shine. Its lightweight texture glides on comfortably, providing a pleasant hydration. It adds a rich color and visually plumps your lips, making your look more expressive. Ideal for both day and evening makeup, it has a dense texture, doesn’t bleed or streak, and feels incredibly comfortable on the lips.',
      hy: 'Morena Cosmetics Ultra Shine շրթունքների փայլը ձեր շուրթերին կհաղորդի գայթակղիչ դեղձի փայլ: Դրա թեթև հյուսվածքը հարմարավետորեն սահում է՝ ապահովելով հաճելի խոնավացում: Այն ավելացնում է հարուստ գույն և տեսողականորեն լցնում է ձեր շուրթերը՝ դարձնելով ձեր տեսքն ավելի արտահայտիչ: Այն իդեալական է ինչպես ցերեկային, այնպես էլ երեկոյան դիմահարդարման համար, ունի խիտ հյուսվածք, չի թափվում կամ չի թողնում շերտեր, և աներևակայելիորեն հարմարավետ է շուրթերի վրա:',
      ru: 'Блеск для губ Morena Cosmetics Ultra Shine подарит вашим губам соблазнительное персиковое сияние. Его легкая текстура комфортно ложится на губы, обеспечивая приятное ощущение увлажнения. Блеск добавит вашим губам сочный цвет и визуально увеличит их объем, делая ваш образ более выразительным. Идеально подходит для создания как дневного, так и вечернего макияжа. Имеет плотную текстуру, не течет и не плешивит, очень комфорный на губах.',
    },
    price: 680,
    images: [
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-44-00-eoJgIIB2pZihmYTz4i52s7YUcACK24.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1082-VC3zfSEkeFNQ5b6v9B1HByw2lwMlh4.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/IMG_1075_jpg-bc3rs1hwFSxRm84rDsTX8hWz9dbUXn.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-33-24-j8WQwCZTx0tBzSf0rEarxpMDO86wJz.JPG',
      'https://kyg4pk2fhp9o45lo.public.blob.vercel-storage.com/Facetune_02-11-2025-18-34-27-DshdFmzOlbDPCGchNHPPtByWaPTGAT.JPG',
    ],
    videos: [],
    category: 'lip_gloss',
    size: '5ml',
    sku: 'CSM-LG-005',
    stockQuantity: 20,
    featured: false,
  },
]

export const categories: CategoryOption[] = [
  {
    value: 'cosmetic_sponges',
    label: {
      en: 'Cosmetic Sponges',
      hy: 'Kosmetik Spongeнер',
      ru: 'Косметические спонжи',
    },
  },
  {
    value: 'lip_liner',
    label: {
      en: 'Lip Liner',
      hy: 'Shafertaguyi Matok',
      ru: 'Карандаш для губ',
    },
  },
  {
    value: 'blush',
    label: { en: 'Blush', hy: 'Ereseski Eranger', ru: 'Румяна' },
  },
  { value: 'stick', label: { en: 'Stick', hy: 'Stick', ru: 'Стик' } },
  {
    value: 'lip_gloss',
    label: { en: 'Lip Gloss', hy: 'Shafertaguy Blesk', ru: 'Блеск для губ' },
  },
  {
    value: 'highlighter',
    label: { en: 'Highlighter', hy: 'Lavsatsun Eranger', ru: 'Сияющие румяна' },
  },
  {
    value: 'concealer',
    label: { en: 'Concealer', hy: 'Konsilyator', ru: 'Консилер' },
  },
]

export const allSizes = [...new Set(products.map((p) => p.size))].sort()

/** Returns the localized display label for a category value */
export function getCategoryLabel(value: Category, locale: Locale): string {
  return categories.find((c) => c.value === value)?.label[locale] ?? value
}

export const getFeaturedProducts = () => products.filter((p) => p.featured)
export const getBestsellers = () => products.filter((p) => p.bestseller)
export const getProductById = (id: string) => products.find((p) => p.id === id)
export const getProductsByCategory = (category: Category) =>
  products.filter((p) => p.category === category)
